# .github/workflows/ci.yml
name: Node.js CI  # CI의 이름

on:
  # pull_request:  # pull request가 생성될 때마다 실행
  #   branches:
  #     - main  # main 브랜치에 대한 PR에 대해 실행
  push:  # push 이벤트가 발생할 때마다 실행, 트리거설정?
    branches:
      - main  # main 브랜치에 대한 push 이벤트에 대해 실행, * 는 모든 branch, on: push 로도 전체 branch 반영가능
    # paths: paths는 GitHub Actions의 워크플로우에서 특정 파일이나 디렉터리에 대한 변경 사항이 있을 때만 해당 워크플로우를 실행하도록 지정하는 데 사용

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16, 18, 20]  # 사용할 Node.js 버전 (예: 16)

    steps:
    - name: Checkout repository (코드 복사)  # 코드 체크아웃 단계
      uses: actions/checkout@v2  # GitHub 리포지토리의 코드를 체크아웃,리포지토리의 코드를 GitHub Actions 워크플로우에서 사용할 수 있도록 체크아웃(복사)하는 기능을 제공
      # @v2 : github action에서 제공하는 checkout기능의 버전
    - name: Set up Node.js ${{ matrix.node-version }} (노드 버전 세팅)  # Node.js 설정 단계
      uses: actions/setup-node@v2  # Node.js 환경 설정
      with:
        node-version: ${{ matrix.node-version }}  # 매트릭스에서 정의한 Node.js 버전 사용

    - name: npm캐시 사용하기  # npm 의존성 캐시 단계
      uses: actions/cache@v3  # 캐시 액션 사용
      with:
        path: ~/.npm  # npm 캐시 경로
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}  # 캐시 키 설정
        restore-keys: |
          ${{ runner.os }}-npm-  # 키가 없을 때 사용할 기본 키

    - name: 의존성 설치  # 의존성 설치 단계
      run: npm ci  # npm을 사용하여 의존성 설치

    - name: 테스트 실행  # 테스트 실행 단계
      run: npm test  # npm 테스트 명령어로 테스트 실행
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_DB: test_db
