# .github/workflows/ci.yml
name: Node.js CI  # CI의 이름

on:
  # pull_request:  # pull request가 생성될 때마다 실행
  #   branches:
  #     - main  # main 브랜치에 대한 PR에 대해 실행
  push:  # push 이벤트가 발생할 때마다 실행, 트리거설정?
    branches:
      - main  # main 브랜치에 대한 push 이벤트에 대해 실행, * 는 모든 branch, on: push 로도 전체 branch 반영가능
    # paths: paths는 GitHub Actions의 워크플로우에서 특정 파일이나 디렉터리에 대한 변경 사항이 있을 때만 해당 워크플로우를 실행하도록 지정하는 데 사용

jobs:
  test_name:  # 작업 이름
    runs-on: ubuntu-latest  # 작업을 실행할 환경

    strategy:
      matrix:
        node-version: [16, 18, 20]  # 사용할 Node.js 버전 (예: 16)

    steps:
    - name: 1. Checkout repository (코드 복사)  # 코드 체크아웃 단계
      uses: actions/checkout@v4  # GitHub 리포지토리의 코드를 체크아웃,리포지토리의 코드를 GitHub Actions 워크플로우에서 사용할 수 있도록 체크아웃(복사)하는 기능을 제공
      # @v4 : github action에서 제공하는 checkout기능의 버전
    - name: 2. Set up Node.js ${{ matrix.node-version }} (노드 버전 세팅)  # Node.js 설정 단계
      uses: actions/setup-node@v4  # Node.js 환경 설정
      with:
        node-version: ${{ matrix.node-version }}  # 매트릭스에서 정의한 Node.js 버전 사용
        cache: 'npm'
          
    - name: 4. 의존성 설치  # 의존성 설치 단계
      run: npm ci  # npm을 사용하여 의존성 설치

    - name: 5. 테스트 실행  # 테스트 실행 단계
      run: npm test  # npm 테스트 명령어로 테스트 실행
